
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/components/ThemeProvider";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "MediQueue ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en" suppressHydrationWarning>

  <body
    className={`antialiased bg-white dark:bg-black text-black dark:text-white`}
  >
    <ThemeProvider>
      <AuthProvider>
        <div className="flex flex-col min-h-screen">
          <Navbar />

          <main className="flex-1 w-full">
            {children}
          </main>

          <Footer />

        </div>

        <Toaster position="top-center" />
      </AuthProvider>
    </ThemeProvider>

  </body>
  
</html>
  );
}
