import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/components/ThemeProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MediQueue ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en" suppressHydrationWarning>

  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black text-black dark:text-white`}
  >
    <ThemeProvider>

      <div className="flex flex-col min-h-screen">
        <Navbar />

        <main className="flex-1 w-full">
          {children}
        </main>

        <Footer />

      </div>

    </ThemeProvider>

  </body>
  
</html>
  );
}
