
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/components/ThemeProvider";
import Footer from "@/components/Footer";


export const metadata = {
  title: "MediQueue ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en" suppressHydrationWarning>

  <body
    className={`antialiased bg-white dark:bg-black text-black dark:text-white`}
  >
    <ThemeProvider>

      <div className="flex flex-col min-h-screen">
        <Navbar />

        <main className="flex-1 w-full">
          {children}
        </main>

        <Footer />

      </div>

    </ThemeProvider>

  </body>
  
</html>
  );
}
